### ISSUE TITLE
dequeueFromNextBatch Error - outputs stuck in batch

### ISSUE THREAD

**Issue by xsats** [SatoshiPortal/batcher#3]
A few days ago I deployed the batcher on the `features/batching` branch of Cyphernode, and I have since been testing/experimenting with it. 

First off - incredible project guys, can't thank you enough for open sourcing this - it will be of immense help. It's been working like a dream so far, and I really like the design and batcher structure.

The only issue I've encountered so far is with attempting to cycle through a batcher to dequeue all outputs. The first couple of `dequeueFromNextBatch` calls worked fine, but for the remainder I encounter the following for each individual request:

`{
  code: -32600,
  message: 'An unknown error occurred',
  data: { batchRequestId: 31 }
}`

Now, when attempting to simply remove one of the failed 'dequeues' individually, I get the same error.

When calling `getBatchDetails` on the batch, I can see that the outputs remain in the batch - so it seems the outputs are now stuck in the batch. On a related note, it may be useful to have a `deleteBatch` method.

In `batcher.log`, the only extra related info is:
`^[[34mdebug^[[39m: Batcher.dequeueFromNextBatch, there was an error calling Cyphernode. {"timestamp":"2020-09-18T09:34:44.809Z"}`

I'm not too sure where else to look to debug this particular issue, but in hindsight I suspect that cycling through a batch to delete batchRequests was a stupid thing to do and likely overloaded Cyphernode.

Any pointers on how to debug further would be really appreciated!

**Comment by Kexkey** [comment]
Do you see anything in the proxy's logs?  BTW you can now look at the logs in the log directory, instead of using docker's logs.

I had an inconsistency between the Batcher DB and the Cyphernode DB during my tests once.  I couldn't find the exact problem, I think I got a bug on the Batcher but not on CN and so CN inserted a batch requests in its DB but the Batcher did not, or something like that.

I need to add more "managing" functionalities to the Batcher (see your other opened issue) so we can see what's going on between the Batcher and CN without having to use command-line SQL requests between the containers.

**Comment by xsats** [comment]
This is all I can see in the proxy.log. Looks like the batchRequest is missing from the proxy db. 

`2020-09-18T14:31:27+0000 14791 [main] step=1
2020-09-18T14:31:27+0000 14791 [main] line={"outputId":28}
2020-09-18T14:31:27+0000 14791 Entering removefrombatch()...
2020-09-18T14:31:27+0000 14791 [removefrombatch] id=28
2020-09-18T14:31:27+0000 14791 sqlite3 -cmd ".timeout 20000" /proxy/db/proxydb "SELECT batcher_id FROM recipient WHERE id=28"
2020-09-18T14:31:27+0000 14791 Last return code: 0
2020-09-18T14:31:27+0000 14791 Entering response_to_client()...
2020-09-18T14:31:28+0000 14791 [main] exiting
2020-09-18T14:31:28+0000 14791 [requesthandler] exiting
2020-09-18T14:31:37+0000 14867 Entering main()...
2020-09-18T14:31:37+0000 14867 [main] line=GET /getblockchaininfo HTTP/1.0`

What you described regarding an inconsistency between the CN and Batcher DBs sounds very much related. 
I'm a wee bit confused as to how this could be happening though - don't both the `getOngoingBatches` and `dequeueFromNextBatch` methods interact directly with the same batcher DB, since they are both Batcher methods? In which case should they not both be querying the same database?

**Comment by Kexkey** [comment]
Yes it's on my todo list to add more robustness in the databases consistency.

CN has its own DB and so has the Batcher.  Unfortunately, they are not totally synced, in the sense that if you bypass the Batcher and add/delete an output to the current batch directly via the CN API, the Batcher won't know about it.

I decided to postpone those database checks for a later release, but I guess I should prioritize it.  Right now, Batcher's getBatchDetails and getOngoingBatches don't call Cyphernode's corresponding endpoints.  It uses its own database.  I need to add sync logic.

Now I don't know how that happened in your case... did it crash or did something strange happen before?

**Comment by xsats** [comment]
Thanks @Kexkey, understand now.

I just tested cyphernode using the getbatchdetails endpoint and you were spot on - the batch was empty (my little script had successfully emptied the batch on cyphernode), which explains why the subsequent `dequeueFromNextBatch` calls returned errors. It seems that the batcher just failed to sync the database correctly after the dequeueing.

Sorry to waste your time - I didn't think to check for discrepancy between the two systems!

**Comment by Kexkey** [comment]
Cool!  You're not wasting my time, on the contrary, this kind of exchange will help improve the project!  Thank you!
