### ISSUE TITLE
Inconsistent Error Response Objects

### ISSUE THREAD

**Issue by xsats** [SatoshiPortal/batcher#5]
Hi @Kexkey!

I noticed when testing invalid input, that the structure of the error response object is different depending on the type of error.

For example, the object returned for an "Invalid arguments" error (in this case amount = 0):

```
{
  "id": 1,
  "error": {
    "code": -32600,
    "message": "Invalid arguments",
    "data": {
      "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
      "amount": 0,
      "batcherId": 2
    }
  }
}
```

Compared to this response in the case of an invalid address:

```
{
  "id": 1,
  "error": {
    "message": {
      "result": null,
      "error": {
        "code": -32700,
        "message": "Invalid address",
        "data": {
          "address": "hjkfaklshfkjsabf7a48fga",
          "amount": 0.01115399,
          "batcherId": 2
        }
      }
    },
    "data": {
      "address": "hjkfaklshfkjsabf7a48fga",
      "amount": 0.01115399,
      "batcherId": 2
    }
  }
}
```

At the moment this makes parsing errors in the response a bit awkward, albeit a minor issue, particularly since we have our own validation which should catch invalid input before a request is made to batcher

**Comment by Kexkey** [comment]
You're right!  I'll fix that.

Explanation: the former is a validation done by the Batcher itself; the latter is an error response from Cyphernode.

Thanks!

**Comment by Kexkey** [comment]
The same problem appears in every call.  I fixed it, I'll push the fix in the dequeueandpay branch ... I'll let you know when it's there.  Thanks again!

**Comment by Kexkey** [comment]
I need more testing but I pushed the new stuff to the features/dequeueandpay branch.  Let me know what you think!  Thanks!

**Comment by xsats** [comment]
Thanks a lot @Kexkey! LGTM
